### ISSUE TITLE
Suspended apps don't let the system sleep correctly. (?)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [devkitPro/libctru#349] opened 2017-03-26 01:44 UTC
I don't actually know if this is a ctrulib issue or not, but I suspect it is, so I'm reporting it here.

Programs compiled with ctrulib 1.2.0 don't seem to correctly let the 3DS sleep when putting the 3DS to sleep while the program is suspended and the system is in the Home menu. Specifically,

- Start an app.
- Press Home to return the Home menu, but don't close the app.
- Shut the 3DS.

If you do this on an official app or game, the power light will start pulsing slowly, and the Wifi light will dim. However, on programs compiled with ctrulib 1.2.0, the power light stays fully lit and the Wifi light does not dim.

I don't know exactly if this means that some process isn't put to sleep correctly, or if it just means that someone neglected to send commands to the LED for this situation, but it seems concerning.

Putting an app to sleep while it's not suspended behaves like an official app/game, with the pulsing and dimmed lights.

**Comment by AdmiralCurtiss** [comment] 2017-03-26 01:46
Oh, and perhaps I should mention this, I was testing this on an European New 3DS with A9LH/Luma on firmware 11.3.0. Just in case it's relevant.

**Comment by WinterMute** [comment] 2017-07-16 22:14
confirmed with 1.3.0, b9s/Luma & 11.5 on o3ds

**Comment by fincs** [comment] 2020-06-16 12:07
I believe this should be fixed as of 7171a87d53fe3998e76d380707f3a6cac54c074c. The cause of this was forgetting to call APT_ReplySleepNotificationComplete when the application was suspended.

**Closed by fincs** 2020-06-16 12:07 UTC
Labels: APT, bug
